---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  namespace: test-rui
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: docker.artifactory.ba.heg.com:443/yorg/haproxy:alpine3.15
        volumeMounts:
        - name: haproxyconfig
          mountPath: "/usr/local/etc/haproxy"
          readOnly: true
        ports:
        - containerPort: 5432
      volumes:
      - name: haproxyconfig
        configMap:
          name: haproxyconfig
